using Microsoft.Extensions.CommandLineUtils;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace Cogs.Console;

/// <summary>
/// Renders the command reference from the same descriptors used by the CLI.
/// </summary>
internal static class CommandReferenceWriter
{
    internal static string Render(CommandLineApplication application)
    {
        ArgumentNullException.ThrowIfNull(application);

        var output = new StringBuilder();
        output.AppendLine(".. This file is generated by ``cogs generate-command-reference``. Do not edit it by hand.");
        output.AppendLine();
        output.AppendLine("CLI descriptor reference");
        output.AppendLine("========================");
        output.AppendLine();
        output.AppendLine("This reference is generated from the descriptors that configure the COGS");
        output.AppendLine("command-line parser. It is checked in so documentation builds do not need to");
        output.AppendLine("execute the tool, and CI rejects drift between this file and the executable.");
        output.AppendLine();

        foreach (CommandLineApplication command in application.Commands
                     .Where(candidate => candidate.ShowInHelpText)
                     .OrderBy(candidate => candidate.Name, StringComparer.Ordinal))
        {
            string heading = command.Name;
            output.AppendLine($".. _cli-descriptor-{heading}:");
            output.AppendLine();
            output.AppendLine(heading);
            output.AppendLine(new string('-', heading.Length));
            output.AppendLine();
            output.AppendLine(command.Description?.Trim() ?? string.Empty);
            output.AppendLine();
            output.AppendLine("Usage");
            output.AppendLine("~~~~~");
            output.AppendLine();
            string arguments = string.Join(" ", command.Arguments
                .Where(argument => argument.ShowInHelpText)
                .Select(argument => argument.Name));
            output.AppendLine($"``cogs {heading}{(arguments.Length == 0 ? string.Empty : " " + arguments)} [options]``");
            output.AppendLine();

            var visibleArguments = command.Arguments
                .Where(argument => argument.ShowInHelpText)
                .ToArray();
            if (visibleArguments.Length > 0)
            {
                output.AppendLine("Arguments");
                output.AppendLine("~~~~~~~~~");
                output.AppendLine();
                foreach (CommandArgument argument in visibleArguments)
                {
                    output.AppendLine($"``{argument.Name}``");
                    output.AppendLine($"   {argument.Description?.Trim() ?? string.Empty}");
                }
                output.AppendLine();
            }

            var visibleOptions = command.Options
                .Where(option => option.ShowInHelpText)
                .ToArray();
            if (visibleOptions.Length > 0)
            {
                output.AppendLine("Options");
                output.AppendLine("~~~~~~~");
                output.AppendLine();
                foreach (CommandOption option in visibleOptions)
                {
                    string template = option.Template;
                    if (option.OptionType != CommandOptionType.NoValue &&
                        !template.Contains('<', StringComparison.Ordinal) &&
                        !template.Contains('[', StringComparison.Ordinal))
                    {
                        template += " <value>";
                    }

                    output.AppendLine($"``{template}``");
                    output.AppendLine($"   {option.Description?.Trim() ?? string.Empty}");
                }
                output.AppendLine();
            }
        }

        // Checked-in generated documentation uses LF on every platform.
        return output.ToString().Replace(Environment.NewLine, "\n", StringComparison.Ordinal);
    }

    internal static void Write(CommandLineApplication application, string outputFile)
    {
        if (string.IsNullOrWhiteSpace(outputFile))
        {
            throw new ArgumentException("An output file is required.", nameof(outputFile));
        }

        string target = Path.GetFullPath(outputFile);
        string parent = Path.GetDirectoryName(target)
            ?? throw new ArgumentException("The output file must have a parent directory.", nameof(outputFile));
        Directory.CreateDirectory(parent);

        string temporary = Path.Combine(parent,
            $".{Path.GetFileName(target)}.{Guid.NewGuid():N}.tmp");
        try
        {
            File.WriteAllText(temporary, Render(application), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            File.Move(temporary, target, overwrite: true);
        }
        finally
        {
            if (File.Exists(temporary))
            {
                File.Delete(temporary);
            }
        }
    }
}
