language: csharp
solution: Cogs.Console.sln
sudo: required
dist: trusty
osx_image: xcode8.3
dotnet: 2.0.0-preview2-006497
mono: none
os:
  - linux
  - osx

branches:  
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore ./Cogs.Console.sln

script:
  - dotnet build ./Cogs.Console.sln
