version: 1.0.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU

init:
- cmd: git config --global core.autocrlf true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
  - cmd: dotnet --version
  # Temporary until 2.0 is on appveyor, Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -version "2.0.0" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
- cmd: >-
    dotnet --version
    
    dotnet restore ./Cogs.Console.sln --verbosity m

build:
  project: Cogs.Console.sln
  verbosity: minimal

after_build:
- cmd: dotnet publish ./Cogs.Console.sln

test: off

artifacts:
- path: .\Cogs.Console\bin\Release\netcoreapp2.0\publish\
  name: Windows-CogsRelease
