// Copyright (c) 2024 Colectica. All rights reserved
// See the LICENSE file in the project root for more information.
using Cogs.Common;
using Cogs.Model;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Cogs.Publishers;

/// <summary>Publishes a GraphQL projection of a validated COGS model.</summary>
public sealed class GraphQLPublisher
{
    private static readonly Regex GraphQlName = new("^[_A-Za-z][_0-9A-Za-z]*$", RegexOptions.CultureInvariant);

    public string? CogsLocation { get; set; }
    public string? TargetDirectory { get; set; }
    public bool Overwrite { get; set; }

    // Retained for source compatibility. GraphQL schemas do not use XML namespaces.
    public string TargetNamespace { get; set; } = "ddi:3_4";

    /// <summary>Stable projection warnings produced by the last publication.</summary>
    public List<CogsError> Errors { get; } = new();

    public void Publish(CogsModel model)
    {
        ArgumentNullException.ThrowIfNull(model);
        Errors.Clear();
        string target = TargetDirectory ?? throw new InvalidOperationException("Target directory must be specified.");
        DirectoryPublication.Publish(target, Overwrite, staging => PublishCore(model, staging),
            string.IsNullOrWhiteSpace(model.SourceDirectory) ? CogsLocation : model.SourceDirectory);
    }

    private void PublishCore(CogsModel model, string targetDirectory)
    {
        ValidateNames(model);
        Errors.Add(new CogsError(
            ErrorLevel.Warning,
            "PROJ2501",
            "GraphQL exposes COGS cardinality, facet, and ordering constraints as directives; resolvers must enforce those directives.",
            sourcePath: model.SourceDirectory));

        var builder = new StringBuilder();
        AppendHeader(builder, model);
        AppendHelpers(builder);

        foreach (DataType type in model.AllDataTypes.OrderBy(type => type.Name, StringComparer.Ordinal))
        {
            AppendType(builder, model, type);
        }

        AppendQuery(builder, model);
        File.WriteAllText(Path.Combine(targetDirectory, "GraphQL.graphqls"), builder.ToString(), new UTF8Encoding(false));
    }

    private static void AppendHeader(StringBuilder builder, CogsModel model)
    {
        builder.AppendLine("# Generated by COGS 2.0. Do not edit.");
        builder.Append("# Model: ").Append(model.Settings?.Title ?? model.Settings?.Slug ?? "COGS model")
            .Append(" (").Append(model.Settings?.Version ?? "unknown").AppendLine(")");
        builder.AppendLine();
        builder.AppendLine("directive @cogsCardinality(min: String!, max: String!, ordered: Boolean! = false) on FIELD_DEFINITION");
        builder.AppendLine("directive @cogsFacet(minLength: Int, maxLength: Int, pattern: String, enumeration: [String!], minInclusive: String, minExclusive: String, maxInclusive: String, maxExclusive: String) on FIELD_DEFINITION");
        builder.AppendLine("directive @cogsIdentification(position: Int!) on FIELD_DEFINITION");
        builder.AppendLine("directive @cogsDeprecated(namespace: String) on OBJECT | INTERFACE");
        builder.AppendLine();
    }

    private static void AppendHelpers(StringBuilder builder)
    {
        string[] scalars =
        {
            "CogsDecimal", "CogsBigInteger", "CogsDuration", "CogsDateTime", "CogsTime",
            "CogsXsdDate", "CogsGYearMonth", "CogsGYear", "CogsGMonthDay", "CogsGDay",
            "CogsGMonth", "CogsAnyUri", "CogsLanguage"
        };
        foreach (string scalar in scalars)
        {
            builder.Append("scalar ").AppendLine(scalar);
        }

        builder.AppendLine();
        builder.AppendLine("type LangString {");
        builder.AppendLine("  language: CogsLanguage!");
        builder.AppendLine("  value: String!");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("type CogsDate {");
        builder.AppendLine("  DateTime: CogsDateTime");
        builder.AppendLine("  Date: CogsXsdDate");
        builder.AppendLine("  GYearMonth: CogsGYearMonth");
        builder.AppendLine("  GYear: CogsGYear");
        builder.AppendLine("  Duration: CogsDuration");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private void AppendType(StringBuilder builder, CogsModel model, DataType type)
    {
        bool hasConcreteDescendants = HasConcreteDescendants(model, type);
        if (type.IsAbstract)
        {
            AppendDescription(builder, type.Description);
            builder.Append("interface ").Append(type.Name);
            AppendAbstractParentInterfaces(builder, type);
            AppendTypeDeprecation(builder, type);
            builder.AppendLine(" {");
            AppendFields(builder, model, type);
            builder.AppendLine("}");
            builder.AppendLine();
        }
        else if (hasConcreteDescendants)
        {
            AppendDescription(builder, $"Assignable view of {type.Name} and its concrete descendants.");
            builder.Append("interface ").Append(type.Name).Append("Assignable");
            AppendImplementedInterfaces(builder, model, type, includeSelfAssignable: false);
            builder.AppendLine(" {");
            AppendFields(builder, model, type);
            builder.AppendLine("}");
            builder.AppendLine();
        }

        if (!type.IsAbstract)
        {
            AppendDescription(builder, type.Description);
            builder.Append("type ").Append(type.Name);
            AppendImplementedInterfaces(builder, model, type, includeSelfAssignable: hasConcreteDescendants);
            AppendTypeDeprecation(builder, type);
            builder.AppendLine(" {");
            AppendFields(builder, model, type);
            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static void AppendAbstractParentInterfaces(StringBuilder builder, DataType type)
    {
        string[] parents = type.ParentTypes.Where(parent => parent.IsAbstract)
            .Select(parent => parent.Name).Distinct(StringComparer.Ordinal).ToArray();
        if (parents.Length != 0)
        {
            builder.Append(" implements ").Append(string.Join(" & ", parents));
        }
    }

    private static void AppendImplementedInterfaces(
        StringBuilder builder,
        CogsModel model,
        DataType type,
        bool includeSelfAssignable)
    {
        var interfaces = new List<string>();
        interfaces.AddRange(type.ParentTypes.Where(parent => parent.IsAbstract).Select(parent => parent.Name));
        interfaces.AddRange(type.ParentTypes.Where(parent => !parent.IsAbstract && HasConcreteDescendants(model, parent))
            .Select(parent => parent.Name + "Assignable"));
        if (includeSelfAssignable)
        {
            interfaces.Add(type.Name + "Assignable");
        }

        string[] distinct = interfaces.Distinct(StringComparer.Ordinal).ToArray();
        if (distinct.Length != 0)
        {
            builder.Append(" implements ").Append(string.Join(" & ", distinct));
        }
    }

    private void AppendFields(StringBuilder builder, CogsModel model, DataType type)
    {
        IReadOnlyList<Property> properties = CogsTypeSystem.EffectiveProperties(type);
        bool inheritsEmptyInterface = type.ParentTypes.Any(parent =>
            (parent.IsAbstract || HasConcreteDescendants(model, parent)) &&
            CogsTypeSystem.EffectiveProperties(parent).Count == 0);
        if (properties.Count == 0 || inheritsEmptyInterface)
        {
            builder.AppendLine("  _cogsType: String! @deprecated(reason: \"COGS projection metadata for an empty type\")");
        }
        if (properties.Count == 0)
        {
            if (!Errors.Any(error => error.Code == "PROJ2502" && error.ModelPath == type.Name))
            {
                Errors.Add(new CogsError(ErrorLevel.Warning, "PROJ2502",
                    $"Type '{type.Name}' has no effective properties; GraphQL requires a field, so '_cogsType' was added as projection metadata.",
                    sourcePath: type.Path, modelPath: type.Name));
            }
            return;
        }

        foreach (Property property in properties)
        {
            AppendDescription(builder, property.Description, "  ");
            builder.Append("  ").Append(ToCamelCase(property.Name)).Append(": ")
                .Append(GraphQlPropertyType(model, property));
            AppendPropertyDirectives(builder, model, type, property);
            builder.AppendLine();
        }
    }

    private static void AppendPropertyDirectives(StringBuilder builder, CogsModel model, DataType owner, Property property)
    {
        builder.Append(" @cogsCardinality(min: \"").Append(Escape(property.MinCardinality)).Append("\", max: \"")
            .Append(Escape(property.MaxCardinality)).Append("\", ordered: ")
            .Append(property.Ordered ? "true" : "false").Append(')');

        int identificationPosition = owner is ItemType
            ? model.Identification
                .Select((id, index) => (id, index))
                .Where(entry => string.Equals(entry.id.Name, property.Name, StringComparison.Ordinal))
                .Select(entry => entry.index)
                .DefaultIfEmpty(-1)
                .First()
            : -1;
        if (identificationPosition >= 0)
        {
            builder.Append(" @cogsIdentification(position: ").Append(identificationPosition).Append(')');
        }

        var facets = new List<string>();
        if (property.MinLength.HasValue) facets.Add("minLength: " + property.MinLength.Value.ToString(CultureInfo.InvariantCulture));
        if (property.MaxLength.HasValue) facets.Add("maxLength: " + property.MaxLength.Value.ToString(CultureInfo.InvariantCulture));
        if (!string.IsNullOrEmpty(property.Pattern)) facets.Add("pattern: \"" + Escape(property.Pattern) + "\"");
        if (property.Enumeration.Count != 0)
        {
            facets.Add("enumeration: [" + string.Join(", ", property.Enumeration.Select(value => "\"" + Escape(value) + "\"")) + "]");
        }
        AddLexicalFacet(facets, "minInclusive", property.MinInclusive);
        AddLexicalFacet(facets, "minExclusive", property.MinExclusive);
        AddLexicalFacet(facets, "maxInclusive", property.MaxInclusive);
        AddLexicalFacet(facets, "maxExclusive", property.MaxExclusive);
        if (facets.Count != 0)
        {
            builder.Append(" @cogsFacet(").Append(string.Join(", ", facets)).Append(')');
        }

    }

    private static void AppendTypeDeprecation(StringBuilder builder, DataType type)
    {
        if (!type.IsDeprecated && string.IsNullOrWhiteSpace(type.DeprecatedNamespace)) return;
        builder.Append(" @cogsDeprecated");
        if (!string.IsNullOrWhiteSpace(type.DeprecatedNamespace))
        {
            builder.Append("(namespace: \"").Append(Escape(type.DeprecatedNamespace)).Append("\")");
        }
    }

    private static void AppendQuery(StringBuilder builder, CogsModel model)
    {
        builder.AppendLine("type Query {");
        if (model.ItemTypes.Count == 0)
        {
            builder.AppendLine("  _cogsModel: String! @deprecated(reason: \"COGS projection metadata for a model without item types\")");
        }
        foreach (ItemType item in model.ItemTypes.OrderBy(item => item.Name, StringComparer.Ordinal))
        {
            string returnType = GraphQlReferenceType(model, item, allowSubtypes: true);
            builder.Append("  ").Append(ToCamelCase(item.Name)).Append('(');
            builder.Append(string.Join(", ", model.Identification.Select(id =>
                ToCamelCase(id.Name) + ": " + GraphQlPrimitiveType(id.DataTypeName) + "!")));
            builder.Append("): ").Append(returnType).AppendLine();
            builder.Append("  all").Append(item.Name).Append(": [").Append(returnType).AppendLine("!]!");
        }
        builder.AppendLine("}");
    }

    private static string GraphQlPropertyType(CogsModel model, Property property)
    {
        string elementType;
        if (property.DataType is null || property.DataType.IsXmlPrimitive)
        {
            elementType = GraphQlPrimitiveType(property.DataTypeName);
        }
        else
        {
            elementType = GraphQlReferenceType(model, property.DataType, CogsTypeSystem.AllowsSubtypes(property));
        }

        if (!string.Equals(property.MaxCardinality, "1", StringComparison.Ordinal))
        {
            return $"[{elementType}!]!";
        }
        return string.Equals(property.MinCardinality, "0", StringComparison.Ordinal) ? elementType : elementType + "!";
    }

    private static string GraphQlReferenceType(CogsModel model, DataType type, bool allowSubtypes)
    {
        if (type.IsAbstract) return type.Name;
        if (allowSubtypes && HasConcreteDescendants(model, type)) return type.Name + "Assignable";
        return type.Name;
    }

    private static string GraphQlPrimitiveType(string name) => name switch
    {
        "string" => "String",
        "boolean" => "Boolean",
        "int" => "Int",
        "float" or "double" => "Float",
        "decimal" => "CogsDecimal",
        "long" or "nonPositiveInteger" or "negativeInteger" or "nonNegativeInteger" or "unsignedLong" or "positiveInteger" => "CogsBigInteger",
        "duration" => "CogsDuration",
        "dateTime" => "CogsDateTime",
        "time" => "CogsTime",
        "date" => "CogsXsdDate",
        "gYearMonth" => "CogsGYearMonth",
        "gYear" => "CogsGYear",
        "gMonthDay" => "CogsGMonthDay",
        "gDay" => "CogsGDay",
        "gMonth" => "CogsGMonth",
        "anyURI" => "CogsAnyUri",
        "language" => "CogsLanguage",
        "langString" => "LangString",
        "cogsDate" => "CogsDate",
        _ => throw new CogsPublicationException($"PROJ2504: GraphQL does not have a mapping for primitive '{name}'.")
    };

    private static bool HasConcreteDescendants(CogsModel model, DataType type) =>
        model.AllDataTypes.Any(candidate => !candidate.IsAbstract && !ReferenceEquals(candidate, type) &&
            CogsTypeSystem.IsAssignableFrom(type, candidate));

    private static void ValidateNames(CogsModel model)
    {
        var outputTypes = new HashSet<string>(new[]
        {
            "Query", "String", "Boolean", "Int", "Float", "ID", "LangString", "CogsDate",
            "CogsDecimal", "CogsBigInteger", "CogsDuration", "CogsDateTime", "CogsTime",
            "CogsXsdDate", "CogsGYearMonth", "CogsGYear", "CogsGMonthDay", "CogsGDay",
            "CogsGMonth", "CogsAnyUri", "CogsLanguage"
        }, StringComparer.Ordinal);
        var queryFields = new HashSet<string>(StringComparer.Ordinal);
        foreach (DataType type in model.AllDataTypes)
        {
            RequireGraphQlName(type.Name, type.Path, type.Name);
            if (!outputTypes.Add(type.Name))
            {
                throw new CogsPublicationException($"PROJ2505: GraphQL output type name '{type.Name}' collides with a helper or generated type.");
            }
            if (!type.IsAbstract && HasConcreteDescendants(model, type) && !outputTypes.Add(type.Name + "Assignable"))
            {
                throw new CogsPublicationException($"PROJ2505: GraphQL output type name '{type.Name}Assignable' is generated more than once.");
            }
            foreach (Property property in CogsTypeSystem.EffectiveProperties(type))
            {
                RequireGraphQlName(ToCamelCase(property.Name), type.Path, type.Name + "." + property.Name);
            }
        }
        foreach (ItemType item in model.ItemTypes)
        {
            string lookup = ToCamelCase(item.Name);
            string list = "all" + item.Name;
            if (!queryFields.Add(lookup) || !queryFields.Add(list))
            {
                throw new CogsPublicationException($"PROJ2505: GraphQL query fields generated for '{item.Name}' collide with another item query.");
            }
        }
        foreach (Property id in model.Identification)
        {
            RequireGraphQlName(ToCamelCase(id.Name), model.SourceDirectory, "Identification." + id.Name);
        }
    }

    private static void RequireGraphQlName(string name, string? path, string modelPath)
    {
        if (!GraphQlName.IsMatch(name))
        {
            throw new CogsPublicationException($"PROJ2503: '{modelPath}' cannot be represented as a GraphQL name without changing it.");
        }
    }

    private static string ToCamelCase(string value)
    {
        MatchCollection matches = Regex.Matches(value,
            "[A-Z]+(?=[A-Z][a-z]|[0-9]|$)|[A-Z]?[a-z]+|[0-9]+",
            RegexOptions.CultureInvariant);
        if (matches.Count == 0) return value;
        string[] words = matches.Select(match => match.Value).ToArray();
        return words[0].ToLowerInvariant() + string.Concat(words.Skip(1)
            .Select(word => char.ToUpperInvariant(word[0]) + word[1..].ToLowerInvariant()));
    }

    private static void AppendDescription(StringBuilder builder, string? description, string indent = "")
    {
        if (string.IsNullOrWhiteSpace(description)) return;
        foreach (string line in description.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n').Split('\n'))
        {
            builder.Append(indent).Append("# ").AppendLine(line);
        }
    }

    private static void AddLexicalFacet(List<string> facets, string name, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value)) facets.Add(name + ": \"" + Escape(value) + "\"");
    }

    private static string Escape(string? value) => (value ?? string.Empty)
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal)
        .Replace("\t", "\\t", StringComparison.Ordinal);
}
